### ISSUE TITLE
Dependencies Google svn not working

### ISSUE THREAD

**Issue by FranklinSilva** [pussinboots/angularjs-crypto#13]
Hi,

I just want to let you know that the following links for dependencies aren't working.

http://crypto-js.googlecode.com/svn/tags/3.1.2/build/components/mode-ecb.js
http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js

I had to download via bower the crypto.js

**Comment by pussinboots** [comment]
Hi,

thanks for that advice. I put this files into the project and use it from there. Also updated the documentation.
