### ISSUE TITLE
Changif reqest parameters

### ISSUE THREAD

**Issue by mchl18** [pussinboots/angularjs-crypto#14]
Hello,

I am trying to encode and decode certain fields of a JSON Object.
I really really only want to use de encrypt/decrypt functions on their own but crypto seems to think for some reason that I want to do full query encryption, which results in messing with my queries and rewriting it, basically rendering my requests useless.
It turns the {params:{params}} into {params:query:{params}}.
Is this wanted behaviour? How can I turn it off?

**Comment by pussinboots** [comment]
Hi,

what i understand so far is that you only want to encode and decode by calling the crypto functions yourself. Right ? That is not the wanted behavoir. I will provide a bug fix soon.
