### ISSUE TITLE
Stringifying an object won't crypt the raw data

### ISSUE THREAD

**Issue by amiral84** [pussinboots/angularjs-crypto#3]
Today I made a test where I send an stringified object to server. It seems that if you use
   
    JSON.stringify({object})

the raw data will not be crypted even though in query crypt is set to true. For example if I pass

    JSON.stringify({object})

to userData in following service call:

    myFunction: function(userData){
        return $http.post('/someURL', userData, {crypt: true}).success(function(data){
            return data;
        });
    }

and you console log the sent data you see the actual raw data even if you have put _enc after fields you want to be encrypted. Either this could be fixed in the code or could be added in documentation.

**Comment by pussinboots** [comment]
Hi,

i expand the documentation with a section that explained the Header Content-Type check feature.
There is a two way check for every Response and Request and only if they fulfill both conditions than the decrpytion/encryption process will be accomplished. First it will check if the crypt property is true and then if the Content-Type HTTP Header is equal to 'application/json' or 'application/json_enc'. The new section explain how to add also other Content-Type that you want to be encrypted or decrypted. 
There is also mentioned how you can change the Header Content-Type check implementation itself.

That was not mentioned in the deocumentation before. Maybe that was why your test failed hopefully.

**Comment by pussinboots** [comment]
By the way here is the link to the new documentation pieces. [Documentation Link](https://github.com/pussinboots/angularjs-crypto/blob/master/README.md#configure-the-content-type-header-for-encryptiondecryption)

**Comment by ghost** [comment]
Thank you and sorry for very late reply.
