### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by kgislsompo** [pussinboots/angularjs-crypto#4]
My input JSON contains some null values. My aim is to use same JSON object for 3 forms, like a signup wizard. So obviously it contains null values till it reaches end. In this case, I am getting this error. Can you please help me with a solution?

    TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at crypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:95:23)
    at crypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:100:13)
    at crypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:100:13)
    at crypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:100:13)
    at crypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:100:13)
    at encrypt (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:92:2)
    at request (http://10.100.3.122:9080/Nsure/angularmain/angularjs-crypto.js:22:25)
    at http://10.100.3.122:9080/Nsure/angularmain/angular.min.js:118:217
    at n.a.$get.n.$eval (http://10.100.3.122:9080/Nsure/angularmain/angular.min.js:133:39)    (anonymous function) @ angular.min.js:107b.$get @ angular.min.js:80(anonymous function) @ angular.min.js:118a.$get.n.$eval @ angular.min.js:133a.$get.n.$digest @ angular.min.js:130a.$get.n.$apply @ angular.min.js:133(anonymous function) @ angular.min.js:252c @ angular.min.js:35

I downloaded the latest angular-crypto.js files and it's dependencies. Using it with Angular v1.4.4.

**Comment by pussinboots** [comment]
Hi, can you post here the json object that cause the trouple. Then i can setup a test and fix it.

**Comment by pussinboots** [comment]
Added a null and undefined check at the proper line of code. Let see if it fix it.

**Comment by kgislsompo** [comment]
Let me check it now. BTW I have checked your code and from what I understand, it seems if there is null or undefined value, it will not crypt it. But it'll do for other valid datas. Is that so?

**Comment by pussinboots** [comment]
Hi,

can you provide me the json that you try to encrypt. Then i can setup a test case for that and fix it easily. I don't need real data but json object that has the same structure. I think the problem is you have an null json property some where like {null:"some value"} or a {undefined:"some value"}. Because the error occur by using Object.keys() which iterate over the json field's. 

If you don't want to provide the data here then send me an email to pussinboots666@googlemail.com.

looking forward to fix it.

**Comment by rajkumarpb** [comment]
Same user here. I have cross checked my JSON and made sure I have no undefined/null values as key. I am posting part of my JSON for easy readability. I have just removed a hundred keys after checked them myself.

    {"clientProfileDO":{"clientId":0,"agentId":0,"customerName":"test customer","searchCustomerName":null,"accountCode":0,"contactTypeId":1,"newPPNo":"888888888888","oldPPNo":null,"bussRegNo":null,"contactInsuredStatus":null,"salutationId":1,"nationalityId":2,"raceId":4,"dateOfBirth":"25/11/1985","age":0,"genderId":1,"occupationId":2,"maritalStatusId":2,"businessTypeId":0,"businessDesc":null,"vipStatus":null,"taxRegistered":null,"taxRegistrationNo":null,"taxRegisteredDate":null,"taxRegisteredExpDate":null,"campaignCode":null,"facebookUrl":null,"websiteUrl":null,"permanentAddress1":"aaaaaa","permanentAddress2":null,"permanentAddress3":null,"permanentAddress4":null,"permanentPostCode":85000,"permanentPostCodeDesc":"SEGAMAT","permanentStateId":5,"permanentCountryId":null,"permanentCountryCode":"MY","permanentCountryDesc":null,"corrAddressindicator":null,"corrAddress1":null,"corrAddress2":null,"corrAddress3":null,"corrAddress4":null,"corrPostCode":null,"corrPostCodeDesc":null,"corrStateId":null,"corrCountryId":null,"corrCountryCode":null,"corrCountryDesc":null,"mobileNo":"01111111111","emailId":null,"houseTelNo":null,"houseFaxNo":null,"officeTelNo":null,"officeFaxNo":null,"primaryCheck":null,"remarks":null},"masterClassId":null,"masterNo":null,"mainTypeId":0,"issuedDate":null,"startDate":null,"endDate":null}

**Comment by rajkumarpb** [comment]
Thanks bro! It is working fine now! I appreciate your effort in helping me. Great module from a great guy. Kudos!

**Comment by pussinboots** [comment]
You' re welcome. Can you explain me a little bit your use case scenario of it. So that i get a understanding what you want to achieve by using it and improve it. You can still write me as a eMail. Also get in touch with me if you are missing something.

**Comment by rajkumarpb** [comment]
We have an SPA, which needs this JSON to stay in local storage till the user logs out. And we don't want the user to fiddle with the data because it is some sensitive data.

**Comment by pussinboots** [comment]
Ah okay, I got the point you use to secure the local storage interesting
use case. Thx for sharing. Good luck. I started the project with the
intention to store secure data in a database that is only readable on the
client computer.

**Comment by rajkumarpb** [comment]
I get your idea, but the reason we chose to your plugin is, it was simple. It took us less effort to do what we needed with less effort. And meanwhile, the data is indeed sent to server in encrypted form. The only differentiating factor here is, that the JSON will spend some in local storage before it hit server. That's it!

**Comment by kptcs** [comment]
I am facing the same issue .

Below is the my service for get http request 

 getSD(): Observable<any>  {
  return this.http.get(this.URL+ '/SOMEURL', {responseType: 'json'});
  }

here is my component function 

 getALLSD()
  {
     this.config.getSD().subscribe(
     data => { this.allSD = data['employee']},
     err => console.error(err),
     () => console.log('done loading employee')
      );
      const obj = this.allSD;
      console.log(Object.entries(obj));
  }

when checking in console its showing error

ERROR TypeError: Cannot convert undefined or null to object

when using ngFor its showing the value

<ul>
     <li *ngFor="let person of allSD"> 
    {{ person.name}}
  </li>

Please guide the correct way, I need to see the response in console.

**Comment by kptcs** [comment]
I am facing the same issue .

Below is the my service for get http request

getSD(): Observable {
return this.http.get(this.URL+ '/SOMEURL', {responseType: 'json'});
}

here is my component function

getALLSD()
{
this.config.getSD().subscribe(
data => { this.allSD = data['employee']},
err => console.error(err),
() => console.log('done loading employee')
);
const obj = this.allSD;
console.log(Object.entries(obj));
}

when checking in console its showing error

ERROR TypeError: Cannot convert undefined or null to object

when using ngFor its showing the value

{{ person.name}}
Please guide the correct way, I need to see the response in console.
