### ISSUE TITLE
Cannot read property 'encrypt' of undefined

### ISSUE THREAD

**Issue by matus1997** [pussinboots/angularjs-crypto#6]
Hi,

I don't know why but console always shows me this error:

Cannot read property 'encrypt' of undefined

Don't you have any idea what could have I done wrong?

**Comment by pussinboots** [comment]
Hi,

first an question how you use angularjs-crypto library? 
For me it looks like the crypto-js javascript library is not imported 
<script type='text/javascript' src="http://crypto-js.googlecode.com/svn/tags/3.1.2/build/rollups/aes.js"></script>
. May it helps you.

**Comment by matus1997** [comment]
It seems that everything is loaded correctly.

<img width="601" alt="screen shot 2016-01-01 at 14 25 38" src="https://cloud.githubusercontent.com/assets/9851684/12070984/912e227a-b093-11e5-9410-5358b8f62d76.png">

Console shows me exactly this
<pre>
TypeError: Cannot read property 'encrypt' of undefined
    at CryptoJSCipher.encode (CryptoJSCipher.js:13)
    at crypt (angularjs-crypto.js:97)
    at encrypt (angularjs-crypto.js:91)
    at request (angularjs-crypto.js:22)
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)
    at done (angular.js:10589)
</pre>

**Comment by matus1997** [comment]
Hi,

I solved problem by deleting this line in run():

<pre>cfCryptoHttpInterceptor.plugin = new CryptoJSCipher(CryptoJS.mode.ECB, CryptoJS.pad.Pkcs7, CryptoJS.DES)</pre>

I'm not exactly sure why it didn't work but I'm glad it works perfectly now.

Keep up the good work!

**Comment by pussinboots** [comment]
Hi,

good to here if you delete it from your angularjs run method then the default come in place.
```
this.plugin = new CryptoJSCipher(CryptoJS.mode.ECB, CryptoJS.pad.Pkcs7, CryptoJS.AES);
```
Maybe i found the problem CryptoJS.DES was in your case undefined because of the missing crypto-js javascript file. [See here ](https://code.google.com/p/crypto-js/#DES,_Triple_DES).
May this helps you also if you need DES encryption.

Thanks for using
Feel free to contact me for project purpose.
