### ISSUE TITLE
bower install

### ISSUE THREAD

**Issue by clange79** [pussinboots/angularjs-crypto#8]
When i installed using bower install angularjs-crypto, i got an archived version of 1.3.0 from last year. I had to specify bower install angularjs-crypto#master to get the most recent which has many of your significant fixes. can you please update your registry settings? thanks for working on this project

**Comment by estevezluis1** [comment]
I believe that version 1.3.0 is the latest version for the bower package
https://github.com/pussinboots/angularjs-crypto#bower-versions

**Comment by clange79** [comment]
it is. however, when pulling in on bower, it pulls from https://github.com/pussinboots/angularjs-crypto/archive/v1.3.0.tar.gz which doesn't reflected the current state of the master branch and many of the recent changes that were made.

**Comment by pussinboots** [comment]
I tag new version 1.4.0 should be available with bower now.

**Comment by clange79** [comment]
thanks.
